Openrates provider
oae/openapi pull request #30
Opened 2018-11-01 22:14 UTC by halitogunc

- It contains ```openrates provider``` implementation to open-api.

  - Features we have;

    - List all currencies
    - Convert rates from given base currency to many different currencies we have.
    - Historical rates query support.

2018-11-01 22:17 UTC, yasinuslu requested changes

2018-11-01 22:17 UTC, yasinuslu commented on src/providers/openrates/openrates.resolver.js
> +const moment = require('moment');
It would be better if we use [date-fns](https://github.com/date-fns/date-fns) since we're only using `format`

2018-11-01 22:22 UTC, halitogunc commented on src/providers/openrates/openrates.resolver.js
> +const moment = require('moment');
sounds legit. I will update it.

2018-11-01 22:33 UTC, yasinuslu approved these changes

2018-11-02 14:08 UTC, oae approved these changes

2018-11-02 14:08 UTC, oae commented
LGTM

2018-11-02 14:13 UTC, merged