[WIP] Add kitsu provider
oae/openapi pull request #49
Opened 2018-11-07 20:52 UTC by halitogunc

2018-11-14 18:51 UTC, oae requested changes

2018-11-14 18:51 UTC, oae commented on packages/kitsu/kitsu.resolver.test.js
> +    expect(result).toMatchSnapshot();
We don't use snapshots anymore since data may change and breaks our CI. Take at look at [openlibrary.resolver.test.js](https://github.com/openapi/openapi/blob/master/packages/openlibrary/openlibrary.resolver.test.js#L81)

2018-11-15 18:06 UTC, oae approved these changes

2018-11-15 19:09 UTC, oae commented
LGTM

2018-11-15 19:20 UTC, yasinuslu commented
LGTM

2018-11-15 19:21 UTC, yasinuslu approved these changes

2018-11-15 19:23 UTC, merged